services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - annonces_pg_data:/var/lib/postgresql/data
      - ./migrations:/migrations:ro

volumes:
  annonces_pg_data:
